version: '3.7'

services:

  mysql:
    image: mysql:latest
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    hostname: localhost
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: okay
      MYSQL_DATABASE: hotel
      MYSQL_USER: admin
      MYSQL_PASSWORD: okay
      #MYSQL_ALLOW_EMPTY_PASSWORD=yes
    expose:
      - 3306
    networks:
      - backdb
  #  ports:
  #    - 3306:3306
  #  depends_on:
  #    - backend

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: okay
      MONGO_INITDB_DATABASE: hotel
    #restart: always
    networks:
      - backdb


  backend:
    container_name: backend
    build: ./backend/hotel
    restart: always
    expose:
      - 8080
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hotel?enabledTLSProtocols=TLSv1.2
        SPRING_DATA_MONGODB_HOST: mongo
    networks:
      - backdb
      - frontend
    depends_on:
      - mysql
      - mongo


  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - backdb

  frontend:
    container_name: frontend
    build: ./frontend/frontend
  #  volumes:
  #    - '/app/node_modules'
  #    - '.:/app'
    ports:
      - 4200:4200
    depends_on:
      - backend
    networks:
      - frontend


  nginx:
    build: ./nginx
    container_name: nginx-imse
    restart: always
    ports:
      - "8080:8080"  # for backend
      - "8081:8081"  # for frontend
      - "443:443"   # for frontend with secure browser access(ssl)
    depends_on:
      - frontend
    networks:
      - backdb
      - frontend


networks:
  backdb:
    driver: bridge
  frontend:
    driver: bridge







